app/models.py
from app import db
from datetime import datetime


class User(db.Model):

    __tablename__ = 'users'
    id = db.Column(db.String(100), primary_key=True)
    username = db.Column(db.String(80))
    email = db.Column(db.String(120))
    profileimg = db.Column(db.String(200))
    verifiedstu = db.Column(db.Boolean)
    datecreated = db.Column(db.DateTime)
    trustscore = db.Column(db.Integer)
    anonymous = db.Column(db.Boolean)

    def __init__(self, id, username=None, email=None, profileimg=None,
                 anonymous=True, verifiedstu=False, trustscore=1):
        self.id = id
        self.username = username
        self.email = email
        self.profileimg = profileimg
        self.verifiedstu = verifiedstu
        self.datecreated = datetime.utcnow()
        self.trustscore = trustscore
        self.anonymous = anonymous

    def __repr__(self):
        return '<User {}>'.format(self.id)

    def set_username(self, username):
        self.username = username

    def set_verifiedstu(self, verifiedstu):
        self.verifiedstu = verifiedstu

    def set_profileimg(self, profileimg):
        self.profileimg = profileimg

    def set_trustscore(self, trustscore):
        self.trustscore = trustscore

    def set_anonymity(self, anonymous):
        self.anonymous = anonymous

    @property
    def serialize(self):
        if (self.anonymous is True):
            return {
                'anonymous': True
            }
        return {
            'username': self.username,
            'profileimg': self.profileimg,
            'verifiedstu': self.verifiedstu,
            'datecreated': self.datecreated,
            'anonymous': False
        }


class Sublet(db.Model):

    __tablename__ = 'sublets'
    id = db.Column(db.Integer, primary_key=True)
    creatorid = db.Column(db.String(100), db.ForeignKey('users.id'))
    datecreated = db.Column(db.DateTime)
    datemodified = db.Column(db.DateTime)
    title = db.Column(db.String(100))
    address = db.Column(db.String(100))
    postalcode = db.Column(db.String(6))
    avgrating = db.Column(db.Float)
    latitude = db.Column(db.Float)
    longitude = db.Column(db.Float)
    profileimg = db.Column(db.String(200))
    description = db.Column(db.String(200))
    management = db.Column(db.String(30))

    def __init__(self, creatorid, latitude, longitude, title,
                 address=None, profileimg=None, description=None,
                 avgrating=None, postalcode=None, management=None):
        self.creatorid = creatorid
        self.title = title
        self.latitude = latitude
        self.longitude = longitude
        self.address = address
        self.postalcode = postalcode
        self.avgrating = avgrating
        self.profileimg = profileimg
        self.description = description
        self.datecreated = datetime.utcnow()
        self.management = management

    def __repr__(self):
        return '<Sublet {} at {}, {}>'.format(
            self.id, self.longitude, self.latitude)

    def set_avgrating(self, avgrating):
        self.avgrating = avgrating

    def set_description(self, description):
        self.description = description
        self.datemodified = datetime.utcnow()

    def set_position(self, latitude, longitude):
        self.latitude = latitude
        self.longitude = longitude
        self.datemodified = datetime.utcnow()

    def set_title(self, title):
        self.title = title

    def set_address(self, address):
        self.address = address

    def set_postalcode(self, postalcode):
        self.postalcode = postalcode

    def set_management(self, management):
        self.management = management

    def set_profileimg(self, profileimg):
        self.profileimg = profileimg

    @property
    def serialize(self):
        return {
            'id': self.id,
            'title': self.title,
            'datecreated': self.datecreated,
            'datemodified': self.datemodified,
            'latitude': self.latitude,
            'longitude': self.longitude,
            'description': self.description,
            'avgrating': self.avgrating,
            'profileimg': self.profileimg
        }


class Review(db.Model):

    __tablename__ = 'reviews'
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String(200))
    authorid = db.Column(db.String(100), db.ForeignKey('users.id'))
    subletid = db.Column(db.Integer)
    datecreated = db.Column(db.DateTime)
    datemodified = db.Column(db.DateTime)
    rating = db.Column(db.Integer)

    def __init__(self, authorid, rating, content=None):
        self.authorid = authorid
        self.rating = rating
        self.content = content
        self.datecreated = datetime.utcnow()

    def __repr__(self):
        return '<Review {} by {}>'.format(self.id, self.authorid)

    def set_content(self, content):
        self.content = content
        self.datemodified = datetime.utcnow()

    def set_rating(self, rating):
        self.rating = rating
        self.datemodified = datetime.utcnow()


class Reply(db.Model):

    __tablename__ = "replies"
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String(200))
    reviewid = db.Column(db.Integer, db.ForeignKey('reviews.id'))
    authorid = db.Column(db.String(100), db.ForeignKey('users.id'))
    datecreated = db.Column(db.DateTime)
    datemodified = db.Column(db.DateTime)

    def __init__(self, authorid, reviewid, content=None):
        self.authorid = authorid
        self.reviewid = reviewid
        self.content = content
        self.datecreated = datetime.utcnow()

    def __repr__(self):
        return '<Review {} by {}>'.format(self.id, self.authorid)

    def set_content(self, content):
        self.content = content
        self.datemodified = datetime.utcnow()

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from config import Config

db = SQLAlchemy()
migrate = Migrate(compare_type=True)


def creat_app(config=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    app.app_context().push()

    db.init_app(app)
    migrate.init_app(app, db=db)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from app.ancillary import bp as ancillary_bp
    app.register_blueprint(ancillary_bp)

    from app.api import bp as api_bp
    app.register_blueprint(api_bp, url_prefix='/api')

    app.secret_key = Config.APP_SECRET

    return app


from app import models

app/ancillary/__init__.py
from flask import Blueprint

bp = Blueprint('ancillary', __name__)

from app.ancillary import errors, redirects

app/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__)

from app.api import sublet

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template
from flask import current_app
from flask import redirect
from flask import url_for

from app.main import bp
from app.auth.oauth import requires_auth


@bp.route("/")
def home():
    mapbox_token = current_app.config['MAPBOX_PUBLIC_TOKEN']
    return render_template('home.html', mapbox_token=mapbox_token)


@bp.route('/user/dashboard')
@requires_auth
def user_dashboard():
    return render_template('user/dashboard.html')

app/templates/boilerplate.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="description" content="{{seo_description}}">
  <title>{{seo_title}}</title>
  <link href="https://mononote.azurewebsites.net{{seo_canonical}}" rel="canonical">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="/static/css/app.css" type="text/css">
  {% block header %}{% endblock %}
</head>

<body>
  <content>{% block content %}{% endblock %}</content>
  {% include "footer.html" %}
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
  <script src="https://unpkg.com/react@16/umd/react.production.min.js" crossorigin></script>
  <script src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js" crossorigin></script>
  {% block footer_scripts %}{% endblock %}
</body>

</html>

app/templates/footer.html
<footer>
    
    <h4>contact us</h4>
</footer>

app/templates/home.html
{% extends "boilerplate.html" %}

<!-- SEO Info Starts -->
{% set seo_title = "Homepage" %}
{% set seo_canonical = url_for('main.home') %}
{% set seo_description = "Homepage description" %}
<!-- SEO Info Ends -->

{% block header %}
<script src='https://api.mapbox.com/mapbox-gl-js/v1.4.1/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v1.4.1/mapbox-gl.css' rel='stylesheet' />
{% endblock %}

<!-- Body Content Starts -->
{% block content %}
<h1>Home</h1>
<a href="/auth/login">Login</a>
<div id="adsublet_button_container"></div>
<div id='map' style='width: 400px; height: 300px;' data-publictoken={{mapbox_token}}></div>
<div id="sublet_list_container"></div>
<script>
  const map_bounds = [[-80.594071, 43.394077],[-80.398350, 43.520287]];
  mapboxgl.accessToken = document.getElementById('map').dataset.publictoken;
  var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v11',
    bounds: map_bounds
  });
</script>
<div id='root'></div>
{% endblock %}

{% block footer_scripts %}
  <script src="/static/js/sublet.js" type="text/babel"></script>
{% endblock %}
<!-- Body Content Ends -->

app/templates/user/dashboard.html
{% extends "boilerplate.html" %}

<!-- SEO Info Starts -->
{% set seo_title = "Dashboard" %}
{% set seo_canonical = url_for('main.user_dashboard') %}
{% set seo_description = "Dashboard description" %}
<!-- SEO Info Ends -->

<!-- Body Content Starts -->
{% block content %}
  <h1>Dashboard</h1>
  <a href="/auth/logout">Logout</a>
{% endblock %}

{% block footer_scripts %}
{% endblock %}
<!-- Body Content Ends -->